server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:5173

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1

            - id: food-service-get
              uri: http://localhost:8082
              predicates:
                - Path=/foods/**
                - Method=GET
              filters:
                - StripPrefix=0
                - name: Retry
                  args:
                    retries: 2
                    methods: GET
                    statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,INTERNAL_SERVER_ERROR

            - id: food-service-write
              uri: http://localhost:8082
              predicates:
                - Path=/foods/**
                - Method=POST,PUT,DELETE
              filters:
                - StripPrefix=0

            - id: order-service-get
              uri: http://localhost:8083
              predicates:
                - Path=/orders/**
                - Method=GET
              filters:
                - StripPrefix=0
                - name: Retry
                  args:
                    retries: 2
                    methods: GET
                    statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,INTERNAL_SERVER_ERROR

            - id: order-service-write
              uri: http://localhost:8083
              predicates:
                - Path=/orders/**
                - Method=POST,PUT,DELETE
              filters:
                - StripPrefix=0

            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/payments/**
              filters:
                - StripPrefix=0

            - id: notification-service
              uri: http://localhost:8085
              predicates:
                - Path=/notifications/**
              filters:
                - StripPrefix=0
